spring.application.name=demo


# 接続先URL (localhost:5432 / データベース名)
spring.datasource.url=jdbc:postgresql://localhost:5432/studyaws
spring.datasource.username=superuser
spring.datasource.password=super

# ドライバクラス名
spring.datasource.driver-class-name=org.postgresql.Driver

#myBatis設定
mybatis.mapper-locations=classpath:*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# デバッグ用：実行されるSQLをコンソールに表示
logging.level.com.example.demo.mapper=DEBUG