spring.application.name=demo


# 接続先URL (localhost:5432 / データベース名)
spring.datasource.url=jdbc:postgresql://localhost:5432/studyaws
spring.datasource.username=superuser
spring.datasource.password=super

# ドライバクラス名
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernateの設定（SQLをコンソールに表示するとデバッグが楽です）
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect